# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Ensure Gitea is installed when we are using Keptn to have auto repository provisioning
- include_role:
    name: gitea

- name: Keptn - Source Gitea endpoints
  include_role: 
    name: gitea
    tasks_from: source-endpoints.yml
  when: gitea_internal_endpoint is not defined

- name: Keptn - Source Gitea secrets
  include_role: 
    name: gitea
    tasks_from: source-secret.yml

- name: Keptn - Install Gitea Provisioner service
  ansible.builtin.include_tasks: gitea-provisioner-service.yml

- name: Install Keptn CLI
  include_role:
    name: keptn-cli
  vars:
    force_install: "{{ true | bool }}"

# USING KEPTN V1 HELM REPO
##############

- name: Add a repository
  kubernetes.core.helm_repository:
    name: keptn
    repo_url: https://charts.keptn.sh

- name: Deploy Keptn on Kubernetes cluster
  kubernetes.core.helm:
    name: keptn
    chart_ref: keptn/keptn
    chart_version: "{{ keptn_version }}"
    release_namespace: "{{ keptn_namespace }}"
    create_namespace: true
    wait: true
    wait_timeout: 15m
    values:
      features:
        automaticProvisioning:
          serviceURL: "http://keptn-gitea-provisioner-service.{{ keptn_namespace }}"
      remediationService:
        enabled: true
      bridge:
        versionCheck:
          enabled: false
        installationType: "QUALITY_GATES"
        # Enable to make Keptn look like CloudAutomation
        # lookAndFeelUrl: "{{ keptn_look_and_feel_url }}"
      continuous-delivery:
        enabled: true
        ingressConfig:
          ingress_hostname_suffix: "{{ ingress_domain }}"
          istio_gateway: "default-gateway.istio-ingress"
  register: keptn_helm_chart

- name: Create Ingress
  block:
  - ansible.builtin.template:
      src: keptn-ingress.yml.j2
      dest: /tmp/keptn-ingress.yml
      owner: "{{ ace_box_user }}"
      group: "{{ ace_box_user }}"
      mode: '0644'
  - kubernetes.core.k8s:
      state: present
      src: /tmp/keptn-ingress.yml
      namespace: "{{ keptn_namespace }}"
    register: keptn_ingress
  when: ingress_class != "istio"

- name: Create VirtualService
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: keptn
        namespace: keptn
      spec:
        hosts:
        - "{{ keptn_ingress_domain }}"
        gateways:
        - "istio-ingress/default-gateway"
        http:
        - route:
          - destination:
              host: api-gateway-nginx
              port:
                number: 80
  when: ingress_class == "istio"

- name: Keptn - Source Keptn secrets
  ansible.builtin.include_tasks: source-secret.yml

- name: Keptn - Source Keptn endpoints
  ansible.builtin.include_tasks: source-endpoints.yml
      
- name: Keptn - Authenticate CLI
  shell: "/usr/local/bin/keptn auth --api-token {{ keptn_api_token }} --endpoint {{ keptn_internal_endpoint }}"
  when: keptn_helm_chart.changed or keptn_ingress.changed

- name: Keptn - Install JMeter service
  ansible.builtin.include_tasks: jmeter-service.yml
  when: keptn_jmeter_service_enabled

- name: Keptn - Install Dynatrace service
  ansible.builtin.include_tasks: dynatrace-service.yml

- name: Keptn - Install Helm service
  ansible.builtin.include_tasks: helm-service.yml
  when: keptn_helm_service_enabled

- name: Keptn - Install Synthetic service
  ansible.builtin.include_tasks: synthetic-service.yml
  when: keptn_synthetic_service_enabled

- name: Keptn - Install Collector service
  ansible.builtin.include_tasks: collector-service.yml
  when: keptn_test_collector_service_enabled

- name: Keptn - Install Job Executor service
  ansible.builtin.include_tasks: job-executor-service.yml
  when: keptn_job_executor_service_enabled

# Include Dashboard values
- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/keptn-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file
