
- name: Get k8s cluster info
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: kube-system
  register: k8s_cluster_uid

- name: Set variable for k8s cluster id
  set_fact:
    k8s_cluster_uid: "{{k8s_cluster_uid.resources[0].metadata.uid}}"

- name: Generate token workflow connection
  shell: |
    echo dt0e01.`openssl rand -out /dev/stdout 15 | base32 | tr '[:lower:]' '[:upper:]'`.`openssl rand -out /dev/stdout 40 | base32 | tr '[:lower:]' '[:upper:]'`
  register: edge_connect_token

- name: Generate variable for token
  set_fact:
    edge_connect_token: "{{edge_connect_token.stdout}}"

- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "k8s_settings_token"
    access_token_scope: ["settings.write", "settings.read"]

# - name: Generate random number for an auxiliar connection to the monaco (optional) one
#   set_fact:
#      r: "{{ 1000 | random }}"

# - name: Configure k8s workflow action connector setting
#   uri:
#     url: "{{ dynatrace_tenant_url }}/api/v2/settings/objects?validateOnly=false"
#     method: POST
#     body: "[{\"schemaId\": \"app:dynatrace.kubernetes.connector:connection\",\"schemaVersion\": \"0.1.5\",\"scope\": \"environment\",\"value\": {\"name\": \"edge-connect-{{r}}\",\"uid\": \"{{ k8s_cluster_uid }}\",\"namespace\": \"dynatrace\",\"token\": \"{{edge_connect_token}}\"}}]"
#     body_format: json
#     headers:
#       Authorization: 'Api-Token {{ k8s_settings_token }}'
#       Content-Type: 'application/json; charset=utf-8'
#       accept: application/json
#   register: post_output