- name: edge connect service account
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-serviceaccount.yaml"

- name: edge connect role
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-role.yaml"

- name: edge connect role binding
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-rolebinding.yaml"

- set_fact:
    dt_tenant_gen3_no_protocol: "{{ extra_vars.dt_environment_url_gen3 | regex_search('[^\/\/]*$') }}"

- name: Template secret for edge connect
  ansible.builtin.template:
    src: "edgeconnect-oauth-secret.yaml.j2"
    dest: "{{ role_path }}/templates/edgeconnect-oauth-secret.yaml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: "0644"

- name: Apply secret for edge connect
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect-oauth-secret.yaml"
  delay: 5

- set_fact:
    tenant_id: "{{ dt_tenant_gen3_no_protocol | split('.') }}"

- name: Print response
  debug: "msg='{{ tenant_id[0] }}'"

- name: Template edge connect
  ansible.builtin.template:
    src: "edgeconnect.yaml.j2"
    dest: "{{ role_path }}/templates/edgeconnect.yaml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: "0644"
    
- name: Apply edge connect
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/templates/edgeconnect.yaml"
  delay: 5

- name: Generate credentials
  include_role:
    name: dt-edge-connect
    tasks_from: generate-credentials