# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- hosts: localhost
  connection: local
  become: true
  become_user: "{{ ace_box_user | default(lookup('env','USER')) }}"
  roles:
    # Role "config-v2" is always executed
    # and makes sure that all previous settings
    # are sourced alongside newly enabled/disabled
    - role: config-v2
      tags:
        - always
  # Tool specific roles can be targeted by tags
  tasks:
    - include_role:
        name: init
        apply:
          tags:
            - init
      tags:
        - init
    - include_role:
        name: microk8s
        apply:
          tags:
            - microk8s
      tags:
        - microk8s
    - include_role:
        name: dt-activegate-classic
        apply:
          tags:
            - dt_activegate_classic
      tags:
        - dt_activegate_classic
    - include_role:
        name: dt-operator
        apply:
          tags:
            - dt_operator
      tags:
        - dt_operator
    - include_role:
        name: dt-oneagent-classic
        apply:
          tags:
            - dt_oneagent_classic
      tags:
        - dt_oneagent_classic
    - include_role:
        name: keptn
        apply:
          tags:
            - keptn
      tags:
        - keptn
    - include_role:
        name: monaco
        apply:
          tags:
            - monaco
      tags:
        - monaco
    - include_role:
        name: jenkins
        apply:
          tags:
            - jenkins
      tags:
        - jenkins
    - include_role:
        name: gitea
        apply:
          tags:
            - gitea
      tags:
        - gitea
    - include_role:
        name: gitlab
        apply:
          tags:
            - gitlab
      tags:
        - gitlab
    - include_role:
        name: awx
        apply:
          tags:
            - awx
      tags:
        - awx
    - include_role:
        name: dashboard
        apply:
          tags:
            - dashboard
      tags:
        - dashboard
    - include_role:
        name: app-easytravel
        apply:
          tags:
            - app_easytravel
      tags:
        - app_easytravel
  # - name: Uninstall Gitlab
  #   include_tasks:
  #     file: roles/gitlab/tasks/uninstall.yml
  #     apply:
  #       tags:
  #       - gitlab_uninstall
  #   tags:
  #   - never
  #   - gitlab_uninstall
  # - name: Uninstall Dynatrace ActiveGate
  #   include_tasks:
  #     file: roles/dt-activegate-private-synth-classic/tasks/uninstall.yml
  #     apply:
  #       tags:
  #       - dynatrace_uninstall
  #   tags:
  #   - never
  #   - dynatrace_uninstall
  # - name: Uninstall Dynatrace Operator
  #   include_tasks:
  #     file: roles/dt-operator/tasks/uninstall.yml
  #     apply:
  #       tags:
  #       - dynatrace_uninstall
  #   tags:
  #   - never
  #   - dynatrace_uninstall
  # - name: Uninstall AWX
  #   include_tasks:
  #     file: roles/awx/tasks/uninstall.yml
  #     apply:
  #       tags:
  #       - awx_uninstall
  #   tags:
  #   - never
  #   - awx_uninstall
