#!/usr/bin/env python3
"""
ACE CLI

Combines ansible-playbooks and tagging logic in a single, simple wrapper
"""

import json
import os
import logging
import subprocess
import pwd

import click

CLI_VERSION = '0.2.0'
default_ansible_workdir = os.path.expanduser('~/ansible/')
default_user = pwd.getpwuid(os.getuid())[0]
install_targets = [
    'microk8s',
    'k8s',
    'gitea',
    'gitlab',
    'dt_operator',
    'dt_activegate_classic',
    'dt_oneagent_classic',
    'keptn',
    'monaco',
    'jenkins',
    'dashboard',
    'awx',
    'app_easytravel',
    'app_unguard',
    'app_hipstershop'
]
uninstall_targets = [
    'gitlab',
    'jenkins',
    'app_easytravel'
]
enable_targets = [
    'demo_default',
    'demo_quality_gates_jenkins',
    'demo_security_gates_jenkins',
    'demo_auto_remediation_ansible',
    'demo_quality_gates_gitlab',
    'demo_all',
    'demo_monaco_gitops',
    'demo_ar_workflows_gitlab',
    'demo_release_validation_srg_gitlab',
    'demo_ar_workflows_ansible'
]

def is_external_use_case(use_case):
    if use_case.startswith('http://') or use_case.startswith('https://'):
        return True
    else:
        return False

def get_external_use_case_version(use_case):
    extracted_parts = use_case.split('.git@')

    is_versioned = len(extracted_parts) > 1
    if is_versioned:
        return f"{extracted_parts[0]}.git", extracted_parts[-1]
    else:
        return use_case, 'HEAD'

def check_enable_targets(ctx, param, value):
    if is_external_use_case(value):
        return value
    if value in enable_targets:
        return value
    else:
        raise click.BadParameter(f'Must be one of {enable_targets} or valid link to external use case in format \'http(s)://...\'')

def set_log_level(
  verbosity,
):
    """Helper method to set log level."""
    if verbosity > 1:
        logging.basicConfig(level=logging.DEBUG)
    elif verbosity == 1:
        logging.basicConfig(level=logging.INFO)

    return


@click.group()
@click.option('-v', '--verbose', count=True, help='Prints additional debug messages.')
@click.version_option(version=CLI_VERSION)
def ace(
    verbose
):
    """This tool...

    ACTION can start with "prepare", "enable", "set", "install" or "uninstall".
    "enable" can be followed by an enable target, e.g. "demo_default", "demo_appsec", 
    ..., whereas "install" can be followed by an install target, e.g. "gitlab", ...

    For example:

    $ ace prepare
    > ...

    $ ace enable demo_default
    > ...

    $ ace install gitlab
    > ...
    """
    # If verbose flag is provided, log level will be set to DEBUG
    set_log_level(verbose)


@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
@click.option(
    '--ingress-domain',
    help='Please enter your public domain. If not set you\'ll be prompted during "prepare".',
    envvar='ACE_INGRESS_DOMAIN',
)
@click.option(
    '--ingress-protocol',
    help=(
        'Please enter the protocol you\'re using.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_INGRESS_PROTOCOL',
)
@click.option(
    '--dt-tenant',
    help=(
        'Please enter your Dynatrace tenant URL in the format of'
        'https://[environment-guid].live.dynatrace.com OR'
        'https://[managed-domain]/e/[environment-guid].'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_DT_TENANT',
)
@click.option(
    '--dt-api-token',
    help=(
        'Please enter your Dynatrace API token in format of \'dt0c01. ...\'.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_DT_API_TOKEN',
)
@click.option(
    '--dashboard-user',
    help=(
        'Please enter your ACE-Box dashboard user.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_DASHBOARD_USER',
)
@click.option(
    '--dashboard-password',
    help=(
        'Please enter your ACE-Box dashboard password.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_DASHBOARD_PASSWORD',
)
@click.option(
    '--host-group',
    help=(
        'Please enter a host group the ACE-Box will be assigned to'
    ),
    envvar='ACE_HOST_GROUP',
)
@click.option(
    '--use-case-validation-tests-enabled',
    help='Flag to enable or disable use case validation tests',
    envvar='USE_CASE_VALIDATION_TESTS_ENABLED',
)
@click.option('--extra-var', multiple=True)
@click.option(
    '-f',
    '--force',
    is_flag=True,
    help='Overwrites any confirmation prompts.'
)
def prepare(
    ingress_domain,
    ingress_protocol,
    dt_tenant,
    dt_api_token,
    dashboard_user,
    dashboard_password,
    host_group,
    ansible_workdir,
    user,
    use_case_validation_tests_enabled,
    extra_var,
    force,
):
    """Preparing ACE-Box"""
    logging.info('Preparing ACE-Box...')

    if not ingress_domain:
        ingress_domain = click.prompt('Please enter your public domain', default='127.0.0.1.nip.io')

    if not ingress_protocol:
        ingress_protocol = click.prompt('Please enter the protocol', default='http')

    if not dt_tenant:
        dt_tenant = click.prompt('Please enter your Dynatrace environment URL')

    if not dt_api_token:
        dt_api_token = click.prompt('Please enter your Dynatrace API token')

    if not dashboard_user:
        dashboard_user = click.prompt('Please enter your ACE-Box dashboard user', default='dynatrace')

    if not dashboard_password:
        dashboard_password = click.prompt('Please enter your ACE-Box dashboard password')

    if not use_case_validation_tests_enabled:
        use_case_validation_tests_enabled = click.prompt('Please enter True(default:False) if you want e2e validation tests enabled', default=False)

    logging.debug(f'use_case_validation_tests_enabled is set to: {use_case_validation_tests_enabled}')

    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    ace_config_file_path = f'/home/{user}/.ace/ace.config.yml'

    if os.path.exists(ace_config_file_path):
        if force:
            overwrite_hosts_file = True
        else:
            overwrite_hosts_file = click.confirm(
              f'{ace_config_file_path} already exists. Are you sure you want to overwrite it?'
            )

        if not overwrite_hosts_file:
            click.echo('Chose not to overwrite hosts file. Exiting...')
            return

    ansible_extra_vars = {
        'ace_box_user': user,
        'ingress_domain': ingress_domain,
        'ingress_protocol': ingress_protocol,
        'dynatrace_tenant_url': dt_tenant,
        'dynatrace_api_token': dt_api_token,
        'dashboard_user': dashboard_user,
        'dashboard_password': dashboard_password,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml',
        'use_case_validation_tests_enabled': use_case_validation_tests_enabled,
        'extra_vars': {}
    }
    
    if host_group:
        ansible_extra_vars['host_group'] = host_group

    for var in extra_var:
        extra_var_parts = var.split('=')
        ansible_extra_vars['extra_vars'][extra_var_parts[0]] = "=".join(extra_var_parts[1:])

    subprocess.run((
            f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook -vv ace_box.ace_box.prepare '
            f'--extra-vars \'{json.dumps(ansible_extra_vars)}\''
        ),
        shell=True,
        check=True,
    )
    click.echo('All set! You can now install components.')


@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
@click.argument(
    'target',
    type=click.Choice(
        install_targets,
        case_sensitive=True,
    ),
    nargs=1,
)
def install(
    target,
    ansible_workdir,
    user,
):
    """Installing ACE-Box components"""
    logging.info('Installing ACE-Box ({%s})...', target)

    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    ansible_extra_vars = {
        'ace_box_user': user,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml'
    }

    subprocess.run((
            f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook -vv ace_box.ace_box.main '
            f'--extra-vars \'{json.dumps(ansible_extra_vars)}\' '
            f'--tags "{target}"'
        ),
        shell=True,
        check=True,
    )

    click.echo(f'Successfully installed {target}')
    click.echo("You're welcome!")


@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
@click.argument(
    'target',
    type=click.Choice(
        uninstall_targets,
        case_sensitive=True,
    ),
    nargs=1,
)
def uninstall(
    target,
    ansible_workdir,
    user,
):
    """Uninstalling ACE-Box components"""
    logging.info('Uninstalling ACE-Box ({%s})...', target)

    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    ansible_extra_vars = {
        'ace_box_user': user,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml'
    }
    tag = f'{target}_uninstall'

    subprocess.run((
            f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook -vv ace_box.ace_box.main '
            f'--extra-vars \'{json.dumps(ansible_extra_vars)}\' '
            f'--tags "{tag}"'
        ),
        shell=True,
        check=True,
    )

    click.echo(f'Uninstalled {target}!')


@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
@click.argument(
    'update',
    nargs=1,
)
def set(
    ansible_workdir,
    update,
    user,
):
    """Updating ACE-Box config"""
    [ace_config_key, ace_config_value] = update.split('=')

    logging.info('Updating config for ({%s})...', ace_config_key)

    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    ansible_extra_vars = {
        'ace_box_user': user,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml',
        'ace_config_key': ace_config_key,
        'ace_config_value': ace_config_value
    }

    subprocess.run((
            'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook -vv ace_box.ace_box.config_update '
            f'--extra-vars \'{json.dumps(ansible_extra_vars)}\''
        ),
        shell=True,
        check=True,
    )

    click.echo('All set!')


@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
@click.option(
    '--local',
    help=(
        'If local is set, external use case will not be sourced from remote, but from role on local file system.'
    ),
    envvar='ACE_BOX_EXT_USE_CASE_LOCAL',
    is_flag=True,
    default=False,
)
@click.argument(
    'target',
    callback=check_enable_targets,
    nargs=1,
)
def enable(
    target,
    ansible_workdir,
    user,
    local,
):
    """Enabling ACE-Box use case"""
    logging.info('Preparing ACE-Box for use case \"%s\"...', target)

    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    ansible_extra_vars = {
        'ace_box_user': user,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml',
    }

    if is_external_use_case(target):
        logging.info('Detected external use case')

        external_use_case_src, external_use_case_version = get_external_use_case_version(target)

        ansible_extra_vars.update({
            'use_case_ext_src': external_use_case_src,
            'use_case_ext_version': external_use_case_version,
            'local': local
        })

        subprocess.run((
                f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook ace_box.ace_box.main_v2 '
                f'--extra-vars \'{json.dumps(ansible_extra_vars)}\' '
                f'--tags "use_case_ext"'
            ),
            shell=True,
            check=True,
        )
    else:
        subprocess.run((
                f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook ace_box.ace_box.main_v2 '
                f'--extra-vars \'{json.dumps(ansible_extra_vars)}\' '
                f'--tags "{target}"'
            ),
            shell=True,
            check=True,
        )

    click.echo(f'Successfully installed {target}')
    click.echo("You're welcome!")

@click.command()
@click.option(
    '--ansible-workdir',
    help=('DEPRECATED'),
    envvar='ACE_ANSIBLE_WORKDIR',
)
@click.option(
    '--user',
    help=(
        'Please enter the user ACE-Box components will be installed for.'
        'If not set you\'ll be prompted during "prepare".'
    ),
    envvar='ACE_BOX_USER',
    default=default_user,
)
def destroy(
    ansible_workdir,
    user,
):
    """Destroying ACE-Box configurations"""
    if ansible_workdir:
        logging.warning('Warning: --ansible-workdir is deprecated and will be removed in a future version.')

    logging.info('Destroying ACE-Box configurations')

    ansible_extra_vars = {
        'ace_box_user': user,
        'ace_config_file_path': f'/home/{user}/.ace/ace.config.yml'
    }

    subprocess.run((
            f'ANSIBLE_COLLECTIONS_PATH=/home/{user}/.ansible/collections ansible-playbook ace_box.ace_box.destroy '
            f'--extra-vars \'{json.dumps(ansible_extra_vars)}\''
        ),
        shell=True,
        check=True,
    )

    logging.info('Successfully destroyed ACE-Box configurations!')

ace.add_command(prepare)
ace.add_command(install)
ace.add_command(uninstall)
ace.add_command(set)
ace.add_command(enable)
ace.add_command(destroy)

if __name__ == '__main__':
    # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    ace(auto_envvar_prefix='ACE')