# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
include:
  - remote: "https://gitlab.com/dynatrace-ace/dynatrace-gitlab-library/-/raw/master/dynatrace_event.yaml"

stages:
  - build
  - deploy
  - publish-deployment-event

variables:
  IMAGE_NAME: "$DOCKER_REGISTRY_URL/$RELEASE_PRODUCT"
  IMAGE_TAG: "$RELEASE_BUILD_VERSION"

Build Image:
  image: docker:20.10.16
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 0
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DAEMON_OPTIONS: "--insecure-registry=$DOCKER_REGISTRY_URL"
  services:
    - name: docker:20.10.16-dind
      entrypoint: ["sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS"]
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker info
    - docker build --build-arg BUILD_NUMBER="$SIMPLENODE_BUILD_NUMBER" -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"

Deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  needs: ["Build Image"]
  script:
    - >
      helm upgrade --install $RELEASE_PRODUCT-$RELEASE_INSTANCE helm/simplenodeservice \
        --set image="$IMAGE_NAME:$IMAGE_TAG" \
        --set domain=$INGRESS_DOMAIN \
        --set version=$RELEASE_VERSION \
        --set build_version=$RELEASE_BUILD_VERSION \
        --set ingress.isCanary=$IS_CANARY \
        --set ingress.canaryWeight=$CANARY_WEIGHT \
        --set dt_release_product=$RELEASE_PRODUCT \
        --set dt_owner="$RELEASE_PRODUCT-$RELEASE_STAGE" \
        --set ingress.class="$INGRESS_CLASS" \
        --set ingress.mode=canary \
        --namespace $RELEASE_STAGE --create-namespace \
        --wait
    - sleep 150

Publish Deploy Event:
  extends: .dynatrace_event
  stage: publish-deployment-event
  needs: ["Deploy"]
  variables:
    DYNATRACE_ENV_URL: "$DT_TENANT_URL"
    DYNATRACE_API_TOKEN: "$DT_API_TOKEN"
    DESCRIPTION: "$RELEASE_PRODUCT $RELEASE_BUILD_VERSION deployed"
    CUSTOM_PROPERTIES: '{"namespace":"$RELEASE_STAGE"}'
    EVENT_TYPE: "CUSTOM_DEPLOYMENT"
    DT_RELEASE_PRODUCT: "$RELEASE_PRODUCT"
    DT_RELEASE_STAGE: "$RELEASE_STAGE"
    DT_RELEASE_BUILD_VERSION: "$RELEASE_BUILD_VERSION"
    DEPLOYMENT_NAME: "$RELEASE_PRODUCT"
    DEPLOYMENT_VERSION: "$RELEASE_BUILD_VERSION"
